### ISSUE TITLE
Attestation failure not being returned in the delegate.

### ISSUE THREAD

**Issue by vivdub** [google-home/sample-apps-for-matter-android#154]
HI,

One of our devices is failing in the attestation phase, however, we are not receiving any callback in the delegate using which we can ignore it.
_The device gets commissioned successfully on the IOS._

 Below are some of the logs:
 
 Setting attestation nonce to random value
Setting attestation nonce to random value
Setting attestation nonce from parameters
D  *** Missing DeviceAttestationVerifier configuration at DeviceCommissioner init: using global default, consider passing one in CommissionerInitParams.
Retrieved attestation response. [CONTEXT service_id=336 ]
Retrieved attestation challenge. [CONTEXT service_id=336 ]
Performing device attestation. [CONTEXT service_id=336 ]

Commissioning failed with state Attestation failure. [CONTEXT service_id=336 ]
                                                                                                    m.esk: Device did not pass attestation (error(s)=[4, 11])
                                                                                                    	at m.etp.g(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):40)
                                                                                                    	at m.etj.b(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):0)
                                                                                                    	at m.pdj.f(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):4)
                                                                                                    	at m.plo.run(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:984)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8088)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Showing error status. [CONTEXT service_id=336 ]
                                                                                                    

m.gbg: Device did not pass attestation (error(s)=[4, 11])
                                                                                                    	at m.gim.a(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):28)
                                                                                                    	at m.pse.a(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):4)
                                                                                                    	at m.puj.a(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):0)
                                                                                                    	at m.pui.a(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):6)
                                                                                                    	at m.eiu.b(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):97)
                                                                                                    	at m.pdj.f(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):4)
                                                                                                    	at m.plo.run(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:984)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8088)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
                                                                                                    Caused by: m.esk: Device did not pass attestation (error(s)=[4, 11])
                                                                                                    	at m.etp.g(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):40)
                                                                                                    	at m.etj.b(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):0)
                                                                                                    	at m.pdj.f(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):4) 
                                                                                                    	at m.plo.run(:com.google.android.gms.optional_home@232414065@23.24.14 (100400-0):8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:984) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238) 
                                                                                                    	at android.os.Looper.loop(Looper.java:357) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8088) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at 

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957) 

Thanks

**Comment by pierredelisle** [comment]
Please provide the full logs.

$ adb logcat -c
$ adb logcat > logs.txt
... then use GHSAFM-3p-ecosystem normally

**Comment by vivdub** [comment]
Hi,

I am sending in the logs File.
[logs.txt](https://github.com/google-home/sample-apps-for-matter-android/files/12272873/logs.txt)

Thanks

**Comment by pierredelisle** [comment]
Would you have more details on your device: VID and PID.
Test of production device with proper certs?

**Comment by vivdub** [comment]
VID: 5426
PID: 781

It is a Test device since certification is still pending.

**Comment by pierredelisle** [comment]
Looking at the log:

```
08-07 14:34:14.879  1085  1085 E SetupDeviceViewModel: Commissioning failed with state Attestation failure. [CONTEXT service_id=336 ]
08-07 14:34:14.879  1085  1085 E SetupDeviceViewModel: m.etd: Device did not pass attestation (error(s)=[4, 11])
```

Attestation errors are the following:
```
4: DEVICE_ATTESTATION_VALIDATION_ERROR_TYPE_INVALID_CERTIFICATION_DECLARATION_FORMAT (fatal error)
11: DEVICE_ATTESTATION_VALIDATION_ERROR_TYPE_CHAINED_TO_VALID_TEST_CD_CERT (info)
```

Using prod VID/PID against a test cert is bound to cause issues.

**Comment by vivdub** [comment]
ok.
I will let my Hardware team know about the cause of the issue.
Thanks
