### ISSUE TITLE
The second addition prompt message is too long

### ISSUE THREAD

**Issue by kuyu132** [google-home/sample-apps-for-matter-android#188]
When I used the app to add matter to the nest thermostat for the first time, the addition was successful, then I unbundled it, the count was reduced by one, and I added it for the second time, the following error appeared：

2024-01-08 20:41:06.922  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.922056    9539 chip_logging.cc:17] CHIP: DIS: OperationalSessionSetup[1:BB528773FC78247D]: State change 1 --> 5
2024-01-08 20:41:06.922  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.922759    9539 chip_logging.cc:17] CHIP: CTL: IM invoke() called
2024-01-08 20:41:06.922  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.922911    9539 chip_logging.cc:17] CHIP: DMG: ICR moving to [AddingComm]
2024-01-08 20:41:06.922  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.922964    9539 chip_logging.cc:17] CHIP: DMG: ICR moving to [AddedComma]
2024-01-08 20:41:06.923  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.923238    9539 chip_logging.cc:17] CHIP: EM: <<< [E:52672i S:20240 M:52007743] (S) Msg TX to 1:BB528773FC78247D [77A3] [UDP:[fe80::26e5:fff:feb5:159%wlan0]:5540] --- Type 0001:0A (IM:TimedRequest)
2024-01-08 20:41:06.923  9539-9539  native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.923552    9539 chip_logging.cc:17] CHIP: DMG: ICR moving to [AwaitingTi]
2024-01-08 20:41:06.949  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.949823   11783 chip_logging.cc:17] CHIP: EM: >>> [E:52672i S:20240 M:195840888 (Ack:52007743)] (S) Msg RX from 1:BB528773FC78247D [77A3] --- Type 0001:01 (IM:StatusResponse)
2024-01-08 20:41:06.950  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.950084   11783 chip_logging.cc:17] CHIP: EM: Found matching exchange: 52672i, Delegate: 0xb400007ba23975b8
2024-01-08 20:41:06.950  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.950181   11783 chip_logging.cc:17] CHIP: EM: Rxd Ack; Removing MessageCounter:52007743 from Retrans Table on exchange 52672i
2024-01-08 20:41:06.950  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.950282   11783 chip_logging.cc:17] CHIP: IM: Received status response, status is 0x00 (SUCCESS)
2024-01-08 20:41:06.951  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.951171   11783 chip_logging.cc:17] CHIP: EM: <<< [E:52672i S:20240 M:52007744 (Ack:195840888)] (S) Msg TX to 1:BB528773FC78247D [77A3] [UDP:[fe80::26e5:fff:feb5:159%wlan0]:5540] --- Type 0001:08 (IM:InvokeCommandRequest)
2024-01-08 20:41:06.952  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.952640   11783 chip_logging.cc:17] CHIP: DMG: ICR moving to [CommandSen]
2024-01-08 20:41:06.965  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.965764   11783 chip_logging.cc:17] CHIP: EM: >>> [E:52672i S:20240 M:195840889 (Ack:52007744)] (S) Msg RX from 1:BB528773FC78247D [77A3] --- Type 0001:09 (IM:InvokeCommandResponse)
2024-01-08 20:41:06.965  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.965925   11783 chip_logging.cc:17] CHIP: EM: Found matching exchange: 52672i, Delegate: 0xb400007ba23975b8
2024-01-08 20:41:06.965  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.965979   11783 chip_logging.cc:17] CHIP: EM: Rxd Ack; Removing MessageCounter:52007744 from Retrans Table on exchange 52672i
2024-01-08 20:41:06.966  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.966059   11783 chip_logging.cc:17] CHIP: DMG: ICR moving to [ResponseRe]
2024-01-08 20:41:06.966  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.966269   11783 chip_logging.cc:17] CHIP: DMG: Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
2024-01-08 20:41:06.967  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.967711   11783 chip_logging.cc:17] CHIP: DMG: ICR moving to [AwaitingDe]
2024-01-08 20:41:06.968  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.968617   11783 chip_logging.cc:17] CHIP: EM: <<< [E:52672i S:20240 M:52007745 (Ack:195840889)] (S) Msg TX to 1:BB528773FC78247D [77A3] [UDP:[fe80::26e5:fff:feb5:159%wlan0]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck)
2024-01-08 20:41:06.969  9539-11783 native                  com.google.android.gms.ui            I  I0000 00:00:1704717666.969370   11783 chip_logging.cc:17] CHIP: EM: Flushed pending ack for MessageCounter:195840889 on exchange 52672i
2024-01-08 20:41:06.969  9539-9539  SetupDeviceViewModel    com.google.android.gms.ui            E  Commissioning failed with state Operation failed. [CONTEXT service_id=336 ]
                                                                                                    m.evf: Failed to revoke commissioning window.
                                                                                                    	at m.ewh.onError(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):36)
                                                                                                    	at chip.devicecontroller.ChipClusters$InvokeCallbackImpl.onError(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):3)
                                                                                                    Caused by: chip.devicecontroller.ChipDeviceControllerException: IM Error 0x00000604: Cluster-specific error: 0x04
2024-01-08 20:41:06.971  9539-9539  SetupDeviceChimeraActiv com.google.android.gms.ui            E  Showing error status. [CONTEXT service_id=336 ]
                                                                                                    m.gnw: Failed to revoke commissioning window.
                                                                                                    	at m.gvb.a(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):401)
                                                                                                    	at m.tcx.a(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):60)
                                                                                                    	at m.teg.a(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):84)
                                                                                                    	at m.tgq.a(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):3)
                                                                                                    	at m.tgp.a(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):137)
                                                                                                    	at m.enh.b(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):418)
                                                                                                    	at m.spg.bQ(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):14)
                                                                                                    	at m.sxq.run(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):114)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8194)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: m.evf: Failed to revoke commissioning window.
                                                                                                    	at m.ewh.onError(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):36)
                                                                                                    	at chip.devicecontroller.ChipClusters$InvokeCallbackImpl.onError(:com.google.android.gms.optional_home@234914042@23.49.14 (100400-0):3)
                                                                                                    Caused by: chip.devicecontroller.ChipDeviceControllerException: IM Error 0x00000604: Cluster-specific error: 0x04
2024-01-08 20:41:06.972  9539-9539  WindowOnBackDispatcher  com.google.android.gms.ui            W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2024-01-08 20:41:07.317  1390-1424  WifiHAL                 ven...oogle.wifi_ext-service-vendor  I  Creating message to get link statistics; iface = 47

******************************************
### The defination of the error code:

/**

@def CHIP_ERROR_MESSAGE_TOO_LONG
@brief
A message is too long.
*/
#define CHIP_ERROR_MESSAGE_TOO_LONG CHIP_CORE_ERROR(0x04)

**Comment by kuyu132** [comment]
The defination of the error code:

/**
 *  @def CHIP_ERROR_MESSAGE_TOO_LONG
 *
 *  @brief
 *    A message is too long.
 *
 */
#define CHIP_ERROR_MESSAGE_TOO_LONG                            CHIP_CORE_ERROR(0x04)
