### ISSUE TITLE
onCommissioningRequested() failed - llegalStateException: Commissioning failed with error code [172]

### ISSUE THREAD

**Issue by thejaimin** [google-home/sample-apps-for-matter-android#206]
2024-02-19 17:58:45.699 25843-25882 CTL                     com.google.homesampleapp.default     E  Failed in verifying 'Attestation Information' command received from the device: err 101. Look at AttestationVerificationResult enum to understand the errors
2024-02-19 17:58:45.700 25843-25882 GHSAFM-3p-...onListener com.google.homesampleapp.default     D  onCommissioningStatusUpdate nodeId [8001392132044702307]  stage [AttestationVerification]  errorCode [172]
2024-02-19 17:58:45.700 25843-25882 CTL                     com.google.homesampleapp.default     D  Error on commissioning step 'AttestationVerification': '../../src/controller/CHIPDeviceController.cpp:1078: CHIP Error 0x000000AC: Internal error'
2024-02-19 17:58:45.700 25843-25882 CTL                     com.google.homesampleapp.default     E  Failed to perform commissioning step 8
2024-02-19 17:58:45.700 25843-25882 CTL                     com.google.homesampleapp.default     D  Going from commissioning step 'AttestationVerification' with lastErr = '../../src/controller/CHIPDeviceController.cpp:1078: CHIP Error 0x000000AC: Internal error' -> 'Cleanup'
2024-02-19 17:58:45.701 25843-25882 CTL                     com.google.homesampleapp.default     D  Performing next commissioning step 'Cleanup' with completion status = '../../src/controller/CHIPDeviceController.cpp:1078: CHIP Error 0x000000AC: Internal error'
2024-02-19 17:58:45.701 25843-25882 CTL                     com.google.homesampleapp.default     D  Expiring failsafe on proxy 0xb400007e270aa118
2024-02-19 17:58:45.701 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [AddingComm]
2024-02-19 17:58:45.701 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [AddedComma]
2024-02-19 17:58:45.701 25843-25882 EM                      com.google.homesampleapp.default     D  <<< [E:19764i S:64892 M:202991552] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
2024-02-19 17:58:45.701 25843-25882 IN                      com.google.homesampleapp.default     D  (S) Sending msg 202991552 on secure session with LSID: 64892
2024-02-19 17:58:45.702 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [CommandSen]
2024-02-19 17:58:45.702 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [AwaitingDe]
2024-02-19 17:58:45.702 25843-25882 EM                      com.google.homesampleapp.default     D  <<< [E:19763i S:64892 M:202991553 (Ack:127640303)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2024-02-19 17:58:45.702 25843-25882 IN                      com.google.homesampleapp.default     D  (S) Sending msg 202991553 on secure session with LSID: 64892
2024-02-19 17:58:45.702 25843-25882 EM                      com.google.homesampleapp.default     D  Flushed pending ack for MessageCounter:127640303 on exchange 19763i
2024-02-19 17:58:45.720 25843-25882 EM                      com.google.homesampleapp.default     D  >>> [E:19764i S:64892 M:127640304 (Ack:202991552)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
2024-02-19 17:58:45.720 25843-25882 EM                      com.google.homesampleapp.default     D  Found matching exchange: 19764i, Delegate: 0xb400007cfa6deff8
2024-02-19 17:58:45.720 25843-25882 EM                      com.google.homesampleapp.default     D  Rxd Ack; Removing MessageCounter:202991552 from Retrans Table on exchange 19764i
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [ResponseRe]
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  InvokeResponseMessage =
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  {
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  	suppressResponse = false, 
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  	InvokeResponseIBs =
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  	[
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  		InvokeResponseIB =
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  		{
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  			CommandDataIB =
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  			{
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  				CommandPathIB =
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  				{
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  					EndpointId = 0x0,
2024-02-19 17:58:45.720 25843-25882 DMG                     com.google.homesampleapp.default     D  					ClusterId = 0x30,
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  					CommandId = 0x1,
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  				},
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  				
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  				CommandFields = 
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  				{
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  					0x0 = 0, 
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  					0x1 = "" (0 chars), 
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  				},
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  			},
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  			
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  		},
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  		
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  	],
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  	
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  	InteractionModelRevision = 1
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  },
2024-02-19 17:58:45.721 25843-25882 DMG                     com.google.homesampleapp.default     D  Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
2024-02-19 17:58:45.721 25843-25882 CTL                     com.google.homesampleapp.default     D  Failsafe disarmed
2024-02-19 17:58:45.723 25843-25882 GHSAFM-3p-...onListener com.google.homesampleapp.default     D  onCommissioningStatusUpdate nodeId [8001392132044702307]  stage [Cleanup]  errorCode [0]
2024-02-19 17:58:45.723 25843-25882 CTL                     com.google.homesampleapp.default     D  Successfully finished commissioning step 'Cleanup'
2024-02-19 17:58:45.724 25843-25882 GHSAFM-3p-...onListener com.google.homesampleapp.default     D  BaseCompletionListener onCommissioningComplete(): nodeId [8001392132044702307] errorCode [172]
2024-02-19 17:58:45.725 25843-25882 IN                      com.google.homesampleapp.default     D  SecureSession[0xb400007d5a7228f8]: MarkForEviction Type:1 LSID:64892
2024-02-19 17:58:45.725 25843-25882 SC                      com.google.homesampleapp.default     D  SecureSession[0xb400007d5a7228f8]: Moving from state 'kActive' --> 'kPendingEviction'
2024-02-19 17:58:45.725 25843-25882 EM                      com.google.homesampleapp.default     E  Failed to send Solitary ack for MessageCounter:127640304 on exchange 19764i:../../src/messaging/ExchangeContext.cpp:144: CHIP Error 0x00000002: Connection aborted
2024-02-19 17:58:45.725 25843-25882 DMG                     com.google.homesampleapp.default     D  ICR moving to [AwaitingDe]
2024-02-19 17:58:45.725 25843-25882 IN                      com.google.homesampleapp.default     D  SecureSession[0xb400007d5a7228f8]: Released - Type:1 LSID:64892
2024-02-19 17:58:45.732 25843-25843 GHSAFM-3p-...gRequested com.google.homesampleapp.default     E  onCommissioningRequested() failed
                                                                                                    java.lang.IllegalStateException: Commissioning failed with error code [172]
                                                                                                    	at com.google.homesampleapp.chip.ChipClient$awaitCommissionDevice$2$1.onCommissioningComplete(ChipClient.kt:186)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.onCommissioningComplete(ChipDeviceController.java:335)
2024-02-19 17:58:45.739 25843-25843 GHSAFM-3p-...gRequested com.google.homesampleapp.default     D  Commissioning: commissioningServiceDelegate.sendCommissioningError() succeeded
2024-02-19 17:58:46.849 25843-25843 NsdManager...ceResolver com.google.homesampleapp.default     D  resolve: Timing out
2024-02-19 17:59:01.860 25843-25882 DIS                     com.google.homesampleapp.default     D  Checking node lookup status after 45017 ms
2024-02-19 17:59:01.861 25843-25882 DIS                     com.google.homesampleapp.default     E  OperationalSessionSetup[1:47627B3F3F6EE54D]: operational discovery failed: ../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2024-02-19 17:59:01.867 25843-25882 GHSAFM-3p-...icePointer com.google.homesampleapp.default     E  Unable to get connected device with nodeId 5143809235987916109.
2024-02-19 17:59:01.871 25843-25843 GHSAFM-3p-...dicUpdates com.google.homesampleapp.default     E  Can't get connectedDevicePointer for 5143809235987916109.

**Comment by huytungst** [comment]
Try removing comment-out of HomeScreen.kt line 259.

HomeScreen.kt:259

As-is
`// homeViewModel.setDeviceAttestationDelegate()
`
To-be
`homeViewModel.setDeviceAttestationDelegate()`

**Comment by fxsweety** [comment]
thank you @huytungst Iit solved my issue reported https://github.com/google-home/sample-apps-for-matter-android/issues/217
