### ISSUE TITLE
Getting "Something went wrong" while connecting with Kasa Matter Smart Plug at the last step of provisioning "Connecting to App".

### ISSUE THREAD

**Issue by gsetia402** [google-home/sample-apps-for-matter-android#219]
Can we connect a physical real Matter device with this sample app ? If yes, what changes we need to make in the app ?

**Comment by yinjiangbing** [comment]
So do I,and the log is:
  E  OperationalSessionSetup[1:57845C5EE95A4579]: operational discovery failed: ../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
  D  Device connection failed. Error ../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
  D  onCommissioningStatusUpdate nodeId [6306266940937225593]  stage [FindOperational]  errorCode [50]
  D  Error on commissioning step 'FindOperational': '../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
  E  Failed to perform commissioning step 18
  D  Going from commissioning step 'FindOperational' with lastErr = '../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout' -> 'Cleanup'
  D  Performing next commissioning step 'Cleanup' with completion status = '../../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
  D  onCommissioningStatusUpdate nodeId [6306266940937225593]  stage [Cleanup]  errorCode [0]
  D  Successfully finished commissioning step 'Cleanup'
  D  BaseCompletionListener onCommissioningComplete(): nodeId [6306266940937225593] errorCode [50]
  E  onCommissioningRequested() failed (Ask Gemini)
     java.lang.IllegalStateException: Commissioning failed with error code [50]
     	at com.google.homesampleapp.chip.ChipClient$awaitCommissionDevice$2$1.onCommissioningComplete(ChipClient.kt:186)
     	at chip.devicecontroller.ChipDeviceController.onCommissioningComplete(ChipDeviceController.java:335)
