### ISSUE TITLE
GHSAFM app not working

### ISSUE THREAD

**Issue by livebase** [google-home/sample-apps-for-matter-android#70]
I installed GHSAFM-1.2.2-default-debug.apk on my phone.
The information on my phone is as follows.
- Samsung SM-G970N (Android 12)
After installing the app, when I click the "+" button to add a device, the following error occurs.

****************************************************************************************************************************************
com.google.android.gms.common.api.ApiException: 17: API: CommissioningClient.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
                                                                                                      	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.1.0:3)
                                                                                                      	at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.1.0:1)
                                                                                                      	at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.1.0:1)
                                                                                                      	at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.1.0:7)
                                                                                                      	at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.1.0:2)
                                                                                                      	at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.1.0:24)
                                                                                                      	at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.1.0:12)
                                                                                                      	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                      	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                      	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                      	at android.os.Looper.loop(Looper.java:313)
                                                                                                      	at android.os.HandlerThread.run(HandlerThread.java:67)
****************************************************************************************************************************************

**Comment by pierredelisle** [comment]
```CommissioningClient.API is not available on this device.```

With your phone in debugging mode, could you please run the following and report back.
```
$ adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep -E '(policy|optional)_home'
```

**Comment by livebase** [comment]
Hi pierredelisle,

When my phone is in debug mode, I run the commands you gave me, but nothing prints.

PS C:\> adb shell
beyond0:/ $ dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep -E '(policy|optional)_home'
1|beyond0:/ $

**Comment by pierredelisle** [comment]
Looks like it is not installed on your phone.
Please see https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en_US&gl=US and make sure to install it on your phone.

**Comment by livebase** [comment]
I have confirmed that Google Play Services is installed on my phone.
The picture captured below is the screen when accessing the URL you provided.

![Screenshot_20230118_105706_Google Play Store](https://user-images.githubusercontent.com/85854043/213062817-0658123b-f3ae-4532-8748-9c720a6af500.jpg)

**Comment by pierredelisle** [comment]
Could you try this:

Settings > Apps > See all XX apps > Google Play Services

scroll to the bottom and see which version is installed.

For example: 
version 22.50.54 (190400-499562675)

**Comment by SehribanTas** [comment]
I was having the same problem, when I downloaded the google home application, the problem was solved

**Comment by Yavonix** [comment]
Uninstalling and reinstalling the Google home application also solves the problem for me.

**Comment by livebase** [comment]
The version information of Google Play Services installed on my phone is as follows.
Version 23.03.13 (190408-503260631)

**Comment by tetedoie** [comment]
I had the same issue on a new phone (Pixel 7). The version of the Play Services installed is 23.06.17 (190400-511787759). I'm not sure it's an issue with the Play Services as I have another phone (Pixel 5) running the same Play Service version and GHSAFM is working fine on it. 

I also noticed that the Android settings to manage Matter devices (Google (Services & preferences) > Devices & sharing > Matter devices) was present on the Pixel 5 but not on the Pixel 7. 

I first tried uninstalling and reinstalling GHA but it had no effect. The Pixel 7 was running Android 13 (TD1A.220804.031). I installed the last security patch (TQ1A.221205.011). After installing the update, the Matter devices setting was still not present and GHSAFM still had the API missing issue. I tried to uninstall/reinstall GHA again, and then the Matter devices setting started showing up and GHSAFM was able to start commissioning devices.

**Comment by pierredelisle** [comment]
This is now a known issue. Team is investigating.
If anyone is hitting this issue, please file an Android bug report following the instructions here: https://developer.android.com/studio/debug/bug-report.

And as mentioned above, current workaround is to uninstall and re-install GHA. Eventually it will work. Sorry for the trouble...

**Comment by khushbushah2302** [comment]
The GHSAFM app was working for me. But not it stopped working today. I haven't change / updated anything (like app code / play services etc.)

**Comment by tyui-dev** [comment]
I faced this issue as well.  
to resolve this issue, we need to find out where the error is coming from.  
In my case, logcat showed the following:

```
GooglePlayServicesUtil: com.google.homesampleapp.default requires the Google Play Store, but it is missing.  
GoogleApiManager: The service for com.google.android.gms.common.internal.service.zap is not available:  
ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

and also we can find the following code in the `GooglePlayServicesUtilLight.class`

```java
Preconditions.checkArgument(var3);
String var4 = context.getPackageName();
PackageManager var5 = context.getPackageManager();
int context1;
PackageInfo var20;
if (var18) {
    try {
        var20 = var5.getPackageInfo("com.android.vending", 8256);
    } catch (PackageManager.NameNotFoundException var15) {
        Log.w("GooglePlayServicesUtil", String.valueOf(var4).concat(" requires the Google Play Store, but it is missing."));
        context1 = 9;
        return context1;
    }
} else {
    var20 = null;
}
```

In other words, the result of `ConnectionResult` is based on the result of `GooglePlayServicesUtil`, and internally, it is simply set to query "com.android.vending". This package is installed on most Android systems.  
Nevertheless, the reason the exception is caught is due to package visibility. (Updated in Android 11, API 30)  
[https://developer.android.com/training/package-visibility](https://developer.android.com/training/package-visibility)

In conclusion, we  just need to add the `<queries>` element to the manifest to specify this package.

```xml
<queries>
    <package android:name="com.android.vending" />
</queries>
```

it can be different depending on the error situation.
